apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-dashboard-cert
  namespace: monitoring
spec:
  secretName: grafana-dashboard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.cantalay.com
    - www.grafana.cantalay.com
