apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keycloak.cantalay.com`) || Host(`www.keycloak.cantalay.com`)
      kind: Rule
      services:
        - name: keycloak-keycloakx-http
          port: 80
  tls:
    secretName: keycloak-tls

